namespace MeteoClients.ForecastIo.Settings
{
    public enum SupportedLanguage
    {
        English,
        Arabic,
        Belarusian,
        Bosnian,
        Czech,
        German,
        Greek,
        Spanish,
        French,
        Croatian,
        Hungarian,
        Indonesian,
        Italian,
        Icelandic,
        Cornish,
        Norwegian,
        Dutch,
        Polish,
        Portuguese,
        Russian,
        Slovak,
        Serbian,
        Swedish,
        Tetum,
        Turkish,
        Ukrainian,
        IgpayAtinlay,
        SimplifiedChinese,
        TraditionalChinese
    }
}